### ISSUE TITLE
Feature Request: Filter entries via contenttype

### ISSUE THREAD

**Issue by jgoldhammer** [fboender/harview#5]
Thanks for the tool. It provides me a good way to inspect a larger amount of http requests.

I have a feature request according the filtering of the output.
Would it be possible to restrict via response contenttype?

Examples:
        Content-Type: text/html;charset=UTF-8
        Content-Type: application/json;charset=UTF-8

So if I want to see only the json responses, I can restrict that with a parameter
 harview example.har --content-type JSON -vvv

The parameter value JSON would match application/json and application/json;charset=UTF-8. What do you think?

**Comment by fboender** [comment]
Rather late than never I guess, but I implemented two new arguments:

* `--grep-req GREP_REQ`: Only show requests where Request headers contain GREP_REQ.
* `--grep-res GREP_RES`: Only show requests where Response headers contain GREP_RES.

For example:

```
harview --grep-res 'Content-Type: text' example.har
200 GET https://github.com/fboender/harview
200 GET https://assets-cdn.github.com/assets/frameworks-5aa6d9885579bb2359f66266aee26f3b.css
200 GET https://assets-cdn.github.com/assets/github-183b206659a9b3e5eb123ceb5316db95.css
200 GET https://github.com/fboender/harview/show_partial?partial=tree%2Frecently_touched_branches_list

harview --grep-req 'X-Requested-With: XMLHttpRequest' example.har
200 GET https://github.com/fboender/harview/show_partial?partial=tree%2Frecently_touched_branches_list
```

That should solve your feature request I believe? Note that the filtering is case-sensitive (but headers in .har files are always cased the same).

I'm going to close this feature request in the hopes that this is satisfactory. If not, please don't hesitate to reopen!
